service: team-4-etl

frameworkVersion: '2'


provider:
  iam:  
    role:
      permissionsBoundary: arn:aws:iam::883232869702:policy/ScopePermissions
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: eu-west-1

functions:
  hello:
    handler: handler.hello
  team-4-etl:
    handler: src/team-4-etl/handler.start

custom:
  enterprise:
    collectLambdaLogs: false

